name: CENTURI_Poulain_GlobSeg

channels:
  - defaults
  - nvidia
    
dependencies:
  - python=3.9
  - conda-forge::pyqt=5.12.*
  - cudatoolkit=11.6.*
  - cudnn=8.2.*
  - numpy
  - scipy
  - scikit-image
  - matplotlib-base
  - joblib
  - pip
  - pip:
    - stardist
    - csbdeep
    - tensorflow==2.6.*
    - albumentations
    - gputools